controller_list:
  - name: rover_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_roll
      - shoulder_pitch
      - elbow_pitch 
      - elbow_roll
      - wrist_pitch 
      - wrist_roll
